<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\cpatil\.nuget\packages\select.pdf\23.1.0\contentFiles\any\any\Select.Html.dep" />
    <Content Remove="C:\Users\cpatil\.nuget\packages\select.pdf\23.1.0\contentFiles\any\any\Select.Tools.dep" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ical.Net" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.16" />
    <PackageReference Include="Razorpay" Version="3.3.2" />
    <PackageReference Include="Select.Pdf" Version="23.1.0" />
  </ItemGroup>

</Project>
