// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DbService.Models;

public partial class Assignment6Context : DbContext
{
    public Assignment6Context(DbContextOptions<Assignment6Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingRoom> BookingRooms { get; set; }

    public virtual DbSet<Home> Homes { get; set; }

    public virtual DbSet<LayoutElement> LayoutElements { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Bookings__3214EC0732785EF3");

            entity.Property(e => e.BookingDateFrom).HasColumnType("datetime");
            entity.Property(e => e.BookingDateTo).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CustomerEmail).HasMaxLength(100);
            entity.Property(e => e.CustomerName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CustomerPhone)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Document)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.GuestNumbers).HasColumnName("Guest_Numbers");
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Source)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Home).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.HomeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Bookings__HomeId__4222D4EF");
        });

        modelBuilder.Entity<BookingRoom>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BookingR__3214EC07DE351ECE");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingRooms)
                .HasForeignKey(d => d.BookingId)
                .HasConstraintName("FK__BookingRo__Booki__45F365D3");

            entity.HasOne(d => d.Room).WithMany(p => p.BookingRooms)
                .HasForeignKey(d => d.RoomId)
                .HasConstraintName("FK__BookingRo__RoomI__46E78A0C");
        });

        modelBuilder.Entity<Home>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Homes__3214EC073B1BCAA7");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Location).HasMaxLength(200);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.PricePerDay).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.SUser)
                .HasMaxLength(100)
                .HasColumnName("sUser");
        });

        modelBuilder.Entity<LayoutElement>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LayoutEl__3214EC073FB24EB3");

            entity.Property(e => e.Label).HasMaxLength(100);
            entity.Property(e => e.SUser)
                .HasMaxLength(100)
                .HasColumnName("sUser");

            entity.HasOne(d => d.Home).WithMany(p => p.LayoutElements)
                .HasForeignKey(d => d.HomeId)
                .HasConstraintName("FK__LayoutEle__HomeI__3E52440B");

            entity.HasOne(d => d.Room).WithMany(p => p.LayoutElements)
                .HasForeignKey(d => d.RoomId)
                .HasConstraintName("FK__LayoutEle__RoomI__3F466844");
        });

        modelBuilder.Entity<Room>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Rooms__3214EC071DF9498A");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.PricePerDay).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.SUser)
                .HasMaxLength(100)
                .HasColumnName("sUser");
            entity.Property(e => e.Type).HasMaxLength(50);

            entity.HasOne(d => d.Home).WithMany(p => p.Rooms)
                .HasForeignKey(d => d.HomeId)
                .HasConstraintName("FK__Rooms__HomeId__3A81B327");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}