// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService.Models;

public partial class Booking
{
    public int Id { get; set; }

    public string CustomerName { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerPhone { get; set; }

    public string Message { get; set; }

    public DateTime BookingDateFrom { get; set; }

    public DateTime BookingDateTo { get; set; }

    public int HomeId { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public long Price { get; set; }

    public long GuestNumbers { get; set; }

    public string Document { get; set; }

    public bool IsBooked { get; set; }

    public bool CheckOut { get; set; }

    public virtual ICollection<BookingRoom> BookingRooms { get; set; } = new List<BookingRoom>();

    public virtual Home Home { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}