// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService.Models;

public partial class Booking
{
    public int Id { get; set; }

    public string CustomerName { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerPhone { get; set; }

    public string Message { get; set; }

    public DateTime BookingDateFrom { get; set; }

    public DateTime BookingDateTo { get; set; }

    public int HomeId { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public long Price { get; set; }

    public long GuestNumbers { get; set; }

    public string Document { get; set; }

    public bool IsBooked { get; set; }

    public bool CheckOut { get; set; }

    public long? AdvancePrice { get; set; }

    // Guest detail breakdown
    public int? TotalAdults { get; set; }

    public int? TotalKids { get; set; }

    public int? MaleCount { get; set; }

    public int? FemaleCount { get; set; }

    // Business details (optional)
    public string BusinessName { get; set; }

    public string GstNumber { get; set; }

    // Purpose of visit (optional)
    public string PurposeOfVisit { get; set; }

    public string PurposeOfVisitOther { get; set; }

    // Payment method for advance/initial payment
    public string PaymentMethod { get; set; }

    // Payment method for final/remaining payment
    public string FinalPaymentMethod { get; set; }

    public virtual ICollection<BookingRoom> BookingRooms { get; set; } = new List<BookingRoom>();

    public virtual Home Home { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}
