// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService.Models;

public partial class Home
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public string Description { get; set; }

    public decimal? PricePerDay { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string SUser { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<LayoutElement> LayoutElements { get; set; } = new List<LayoutElement>();

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();
}