// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService.Models;

public partial class LayoutElement
{
    public int Id { get; set; }

    public int? HomeId { get; set; }

    public int? RoomId { get; set; }

    public string Label { get; set; }

    public int? X { get; set; }

    public int? Y { get; set; }

    public int? Width { get; set; }

    public int? Height { get; set; }

    public string SUser { get; set; }

    public virtual Home Home { get; set; }

    public virtual Room Room { get; set; }
}