// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int BookingId { get; set; }

    public string RazorpayOrderId { get; set; }

    public string RazorpayPaymentId { get; set; }

    public string RazorpaySignature { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Booking Booking { get; set; }
}