// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int BookingId { get; set; }

    public string RazorpayOrderId { get; set; }

    public string RazorpayPaymentId { get; set; }

    public string RazorpaySignature { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    // Payment method (Cash, UPI, Card, Online, Bank Transfer, Pay Later)
    public string PaymentMethod { get; set; }

    // Whether this is an advance / partial payment
    public bool IsAdvancePayment { get; set; }

    // Actual amount paid (used when admin confirms with partial/full amount)
    public decimal? AmountPaid { get; set; }

    // Whether the payment is partial (true) or full (false)
    public bool IsPartialPayment { get; set; }

    // Final negotiated room price set by admin at confirmation
    public decimal? FinalRoomPrice { get; set; }

    public virtual Booking Booking { get; set; }
}
