// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbService.Models;

public partial class Room
{
    public int Id { get; set; }

    public int? HomeId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public int? Width { get; set; }

    public int? Height { get; set; }

    public int? PositionX { get; set; }

    public int? PositionY { get; set; }

    public decimal? PricePerDay { get; set; }

    public bool? AllowIndividualBooking { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string SUser { get; set; }

    public virtual ICollection<BookingRoom> BookingRooms { get; set; } = new List<BookingRoom>();

    public virtual Home Home { get; set; }

    public virtual ICollection<LayoutElement> LayoutElements { get; set; } = new List<LayoutElement>();
}